feat(language): add format of C++
Mister-Hope/Mister-Hope.github.io pull request #17
Opened 2020-11-28 17:01 UTC by Eliauk-Ling

2020-11-28 19:37 UTC, Mister-Hope requested changes

2020-11-28 19:37 UTC, Mister-Hope commented on src/code/language/C++/linter/clang-format.md
> +    ![如图](./img/sample3.png "sample3")
你这路径得能对得上啊

2020-11-29 00:16 UTC, Eliauk-Ling commented
.....我忘记改了，改成assets应该可以吧 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Mr.Hope&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月29日(星期天) 凌晨3:37
收件人:&nbsp;&quot;Mister-Hope/Mister-Hope.github.io&quot;<Mister-Hope.github.io@noreply.github.com&gt;;
抄送:&nbsp;&quot;Eliauk-Ling&quot;<949508510@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Mister-Hope/Mister-Hope.github.io] feat(language): add format of C++ (#17)

2020-11-29 04:08 UTC, Mister-Hope commented
另外我记得我让你做了clang format的介绍，在哪里

2020-11-29 04:10 UTC, Eliauk-Ling commented
。。没，上次就说做一个格式化操作的教程吧
那我再改一遍




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mr.Hope"<notifications@github.com&gt;; 
发送时间: 2020年11月29日(星期天) 中午12:08
收件人: "Mister-Hope/Mister-Hope.github.io"<Mister-Hope.github.io@noreply.github.com&gt;; 
抄送: "惠普"<949508510@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Mister-Hope/Mister-Hope.github.io] feat(language): add format of C++ (#17)





 
另外我记得我让你做了clang format的介绍，在哪里
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-29 10:04 UTC, closed without merging